version: '3.8'

services:
  seamless:
    container_name: seamless_django
    image: seamless_django
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/seamless
    ports:
      - "7000:7000"
