version: '3.8'

services:
  seamless:
    container_name: django
    image: seamless_django
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/seamless
    ports:
      - "8000:8000"
