# Generated by Django 3.1 on 2020-08-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undisclosed')], max_length=1)),
                ('conditions', models.ManyToManyField(to='patients.Condition')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'pk'],
            },
        ),
    ]
